import argparse
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor

def build(slides_file, output):
    prs = Presentation()
    title_slide = prs.slides.add_slide(prs.slide_layouts[0])
    title_slide.shapes.title.text = "Presentation"
    title_slide.placeholders[1].text = "Generated by aihub"

    with open(slides_file, encoding="utf-8") as fh:
        lines = [line.rstrip() for line in fh]

    slide = None
    for line in lines:
        if line.startswith("# "):
            slide = prs.slides.add_slide(prs.slide_layouts[1])
            slide.shapes.title.text = line[2:].strip()
        elif line.startswith("- ") and slide is not None:
            tf = slide.placeholders[1].text_frame
            p = tf.add_paragraph()
            p.text = line[2:].strip()
            p.level = 0
        elif line.strip() and slide is not None:
            tf = slide.placeholders[1].text_frame
            p = tf.add_paragraph()
            p.text = line.strip()
            p.level = 1
    prs.save(output)
    print(f"Wrote {output} with {len(prs.slides.__iter__.__self__._sldIdLst)} slides")

def main():
    ap = argparse.ArgumentParser(description="Generate a PPTX from a markdown outline")
    ap.add_argument("output", help="output .pptx path")
    ap.add_argument("slides", help="markdown outline (# title, - bullets)")
    args = ap.parse_args()
    build(args.slides, args.output)

if __name__ == "__main__":
    main()
